#!/bin/bash

if (( $# == 0 )); then
    echo Too few arguments
    exit 1
fi
CUT=2
if (( $# > 1 )); then
    CUT=$2
fi
if (( $# > 3 )); then
    wget -r -np --reject index.html --restrict-file-names=nocontrol --no-host-directories --user="$3" --password="$4" --cut-dirs="$CUT" -c "$1"
elif (( $# > 2 )); then
    wget -r -np --reject index.html --restrict-file-names=nocontrol --no-host-directories --user="$3" --password="$3" --cut-dirs="$CUT" -c "$1"
else
    wget -r -np --reject index.html --restrict-file-names=nocontrol --no-host-directories --cut-dirs="$CUT" -c "$1"
fi

