#!/bin/bash

PAD=2

if (( $# > 0 )); then
    PAD=$1
fi

for a in *.flac; do
    ARTIST=`metaflac "$a" --show-tag=ARTIST | sed s/.*=//g`
    TITLE=`metaflac "$a" --show-tag=TITLE | sed s/.*=//g`
    TRACKNUMBER=`metaflac "$a" --show-tag=TRACKNUMBER | sed s/.*=//g`
    ALBUM=`metaflac "$a" --show-tag=ALBUM | sed s/.*=//g`
    mv "$a" "`printf %0${PAD}g $TRACKNUMBER` - $ARTIST - $ALBUM - $TITLE.flac"
done
